### ISSUE TITLE
archangel___archangel yb analysis

### ISSUE THREAD

**Issue by keheliya** [project-kotinos/issues#106]
Add a yb configuration file to https://github.com/project-kotinos/archangel___archangel.
Instuctions are here: https://github.com/project-kotinos/root/blob/master/README.md 
If you come across problems, add them as comments to this issue.

**Comment by wmuengineer** [comment]
Build passed https://github.com/project-kotinos/archangel___archangel/commits/221a5bb597c8675256b08b5c169e392df33ff279
