### ISSUE TITLE
Vizzuality___gfw yb analysis

### ISSUE THREAD

**Issue by keheliya** [project-kotinos/issues#107]
Add a yb configuration file to https://github.com/project-kotinos/Vizzuality___gfw.
Instuctions are here: https://github.com/project-kotinos/root/blob/master/README.md 
If you come across problems, add them as comments to this issue.

**Comment by wmuengineer** [comment]
Another one successfully build https://github.com/project-kotinos/Vizzuality___gfw/commits/5cef1c747659c767b7c750ec72ee69dd7c42f4d3
