### ISSUE TITLE
lneuhaus___pyrpl yb analysis

### ISSUE THREAD

**Issue by keheliya** [project-kotinos/issues#48]
Add a yb configuration file to https://github.com/project-kotinos/lneuhaus___pyrpl
Instuctions are here: https://github.com/project-kotinos/root/blob/master/README.md 
If you come across problems, add them as comments to this issue.

**Comment by beholders-eye** [comment]
For the .yourbase.yml to work as expected, some of the 'headless' configurations were moved to the yb's anaconda buildpack, available at the version that John released just now: 0.0.31.
