### ISSUE TITLE
buermann___introspective_grape yb analysis

### ISSUE THREAD

**Issue by keheliya** [project-kotinos/issues#63]
Add a yb configuration file to https://github.com/project-kotinos/buermann___introspective_grape.
Instuctions are here: https://github.com/project-kotinos/root/blob/master/README.md 
If you come across problems, add them as comments to this issue.

**Comment by wmuengineer** [comment]
Working mostly. Need to figure out why these tests are failing: https://app.staging.yourbase.io/project-kotinos/buermann___introspective_grape/builds/792eacee-799b-4147-829a-623026a2a877

**Comment by wmuengineer** [comment]
All Gemfiles are building successfully https://github.com/project-kotinos/buermann___introspective_grape/commit/258a4ead28495e5e88e6252cf9e8280b99a6b292
